defaults:
  - logging: default
  - data: owt
  - model: small
  - optimizer: adam
  - hydra: default
  - _self_

model:
  type: diffusion
  diffusion_process: hdlm
  p_uniform: 0.0
  t_eps: 1e-4
  cluster_dict_path: ${hydra:runtime.cwd}/hdlm/clusters/semantic_cluster_dict_gidd-small-p_unif-0.0_64.pt
  cluster_embed_path: ${hydra:runtime.cwd}/hdlm/clusters/semantic_centroids_gidd-small-p_unif-0.0_64.pt
  pretrained_model_name: dvruette/gidd-small-p_unif-0.0
  freeze_embeddings: False
  use_pretrained_embeddings: True
  cluster_size: 64
  gamma: 1.0
  p_perturb: 0.1

training:
  resume: null
  seed: 0
  train_batch_size: 64        # ↓ from 64
  eval_batch_size: 64
  num_train_steps: 5000       # ↓ from 1_000_000
  lr_schedule: cosine
  warmup_steps: 500           # scale down warmup
  low_discrepancy_sampling: True
  dtype: bf16              # safer for debug than bf16
  compile_model: True        # turn off compilation until it’s stable

loss:
  loss_type: hdlm
  loss_weighting: dynamic
  min_loss_weight: 0.0
  max_loss_weight: 2.0
  loss_scale: 1.0
  reduction: tokenmean
  simplified: True
  mask_only: True
  cluster_loss_weight: 1.0
  token_loss_weight: 1.0
  force_transitting_within: False
  force_transitting_between: False
  hard_training: False

logging:
  wandb_entity: thesisws25
  wandb_project: hdlm
  wandb_dir: /lustre/home/jguzelkabaagac/wandb
  run_name: null    # <-- add this line
  
path: hdlm/checkpoints/hdlm-small-cluster_64-gamma_1.0-xi_0.9-owt/-1M  # change to your own checkpoint path
batch_size: 32
num_samples: 256
num_denoising_steps: 512
min_p: 0.0
sampling_parameterization: mdlm
temperature: 1.0
samples_path: samples-small-64-xi_0.9-steps_512-mdlm-force_int-temp_1.0.pt