defaults:
  - logging: default
  - data: lm1b
  - hydra: default
  - _self_

model:
  hidden_size: 768
  cond_dim: 128
  n_blocks: 12
  n_heads: 12
  dropout: 0.1
  max_seq_len: 128
  type: diffusion
  diffusion_process: hdlm
  p_uniform: 0.0
  t_eps: 1e-4
  cluster_dict_path: hdlm/clusters/semantic_cluster_dict_bert-base-uncased_64_lm1b.pt
  cluster_embed_path: hdlm/clusters/semantic_centroids_bert-base-uncased_64_lm1b.pt
  pretrained_model_name: bert-base-uncased
  freeze_embeddings: False
  use_pretrained_embeddings: True
  cluster_size: 64
  gamma: 1.0
  p_perturb: 0.0

training:
  resume: null
  seed: 1
  train_batch_size: 64
  eval_batch_size: 64
  num_train_steps: 1000_000
  lr_schedule: constant
  warmup_steps: 2500
  low_discrepancy_sampling: True
  dtype: bf16
  compile_model: True

optimizer:
  type: adam
  lr: 3e-4
  betas: [0.9, 0.99]
  eps: 1e-9
  weight_decay: 0.02
  grad_clip_norm: 1.0

loss:
  loss_type: hdlm
  loss_weighting: dynamic  # [dynamic, clip, none]
  min_loss_weight: 0.0
  max_loss_weight: 10.0  # 2.0
  loss_scale: 1.0
  reduction: tokenmean
  simplified: False  # GIDD type of loss
  mask_only: True
  cluster_loss_weight: 1.0
  token_loss_weight: 1.0
  force_transitting_within: True
  force_transitting_between: False
  hard_training: False

path: hdlm/checkpoints/lm1b-hdlm-small-cluster_64-gamma_1.0-xi_1.0/-1M  # change to your own checkpoint path
batch_size: 32
num_samples: 256
num_denoising_steps: 512
min_p: 0.0
sampling_parameterization: mdlm
temperature: 1.0
samples_path: samples-lm1b-small-64-steps_512-mdlm-temp_1.0.pt